### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by tridungle** [Surnet/swagger-jsdoc#259]
**Describe the bug**
swagger-jsdoc@7.0.0-rc.6

**To Reproduce**
1. install 
2. config swagger with swagger-jsdoc
3. start the server

**Screenshots**

```
/node-boilerplate//node_modules/swagger-jsdoc/index.js:1
import { prepare, extract, organize, finalize } from './src/specification.js';
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Module._compile (/node-boilerplate/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Object.newLoader [as .js] (/node-boilerplate/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

**Comment by cesco69** [comment]
same for me...

**Comment by Leehee1on** [comment]
same issue.

**Comment by datnguyen199** [comment]
yes, i also got this error, does anyone know how to fix?

**Comment by akshay-nm** [comment]
Why would you convert cjs module to es when it is probably designed to be used with node where majority of stuff is cjs?

**Comment by rahulmathews** [comment]
I also faced the same Issue. I solved this issue temporarily by downgrading the version from v7 to v6 using `npm i swagger-jsdoc@6.1.0`

**Comment by datnguyen199** [comment]
@rahulmathews thank you, it also solved this for me

**Comment by HappyZombies** [comment]
plz fix
