### ISSUE TITLE
I have the problem with 'chokidar' package. 

### ISSUE THREAD

**Issue by stanislavt** [Surnet/swagger-jsdoc#57]
Hi! 

I have installed swagger-json locally. When I try to use ./node_modules/.bin/swagger-json, an error occur. 
```
module.js:472
    throw err;
    ^

Error: Cannot find module 'chokidar'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/stanislav/dev/test/swagger-jsdoc/node_modules/swagger-jsdoc/bin/swagger-jsdoc.js:14:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

I've found out that 'chokidar' package is using in devDependencies. Could you fix the problem?
Correct me please, if I'm wrong.

**Comment by kalinchernev** [comment]
Hi @stanislavt could you please give me also the arguments you're using in the cli?

**Comment by otusweb** [comment]
I'm running into the same issue. 
I'm on Mac OS 10.12.3
installed with npm install swagger-jsdoc -g
ran command: swagger-jsdoc -h

Seem like dev dependencies are not installed when installing the command globally. 
I moved the dependency to the non dev section and did an npm install in the directory and this seem to have solve the issue for me.

**Comment by kalinchernev** [comment]
Hi @otusweb thanks for this remark!
Are you interested in making a small PR for this?

**Comment by kalinchernev** [comment]
It's moved now, please npm update to take new version and try again.

**Comment by otusweb** [comment]
Installed updated version and it works. Thx

**Comment by stanislavt** [comment]
Thank you, @kalinchernev
